[Thesis] Instance Model
UST-EDMM/edmm pull request #25
Opened 2020-10-02 15:42 UTC by mathonto

This PR adds a new application to the EDMM Transformation Framework that enables:

- automated retrieval of instance information of running applications deployed with Kubernetes, OpenStack Heat, Puppet, and AWS CloudFormation
- transformation of the retrieved instance information to a normalized representation using normative component types and a graph-based notation
- transformation of the normalized representation to the standardized TOSCA instance model
- import of the derived TOSCA instance model into the OpenTOSCA container as running application and the automated enrichment with management features using the Management feature enrichment of OpenTOSCA Winery

2020-10-14 11:25 UTC, lharzenetter requested changes
Besides some minor comments, looks really good :)

2020-10-14 11:25 UTC, lharzenetter commented on edmm-instance/src/main/java/io/github/edmm/plugins/kubernetes/KubernetesInstancePluginLifecycle.java
> +        System.out.println("Transformed to OpenTOSCA Service Template Instance: " + serviceTemplateInstance.getCsarId());
also use a logger here

2020-10-14 11:25 UTC, lharzenetter commented on edmm-instance/src/main/java/io/github/edmm/plugins/kubernetes/KubernetesInstancePluginLifecycle.java
> +        System.out.println("Saved YAML for EDMMi to " + yamlTransformer.getFileOutputLocation());
also use a logger here

2020-10-14 11:25 UTC, lharzenetter commented on edmm-instance/src/main/java/io/github/edmm/plugins/kubernetes/api/ApiInteractorImpl.java
> +            e.printStackTrace();
also use a logger here

2020-10-14 11:25 UTC, lharzenetter commented on edmm-instance/src/main/java/io/github/edmm/plugins/kubernetes/api/AuthenticatorImpl.java
> +            e.printStackTrace();
also use a logger here

2020-10-14 11:25 UTC, lharzenetter commented on edmm-instance/src/main/java/io/github/edmm/plugins/kubernetes/util/KubernetesConstants.java
> +public class KubernetesConstants {
abstract

2020-10-14 11:25 UTC, lharzenetter commented on edmm-instance/src/main/java/io/github/edmm/plugins/kubernetes/util/KubernetesPodsHandler.java
> +public class KubernetesPodsHandler {
abstract

2020-10-14 11:25 UTC, lharzenetter commented on edmm-instance/src/main/java/io/github/edmm/plugins/kubernetes/util/KubernetesStateHandler.java
> +public class KubernetesStateHandler {
abstract

2020-10-14 11:25 UTC, lharzenetter commented on edmm-instance/src/main/java/io/github/edmm/plugins/puppet/model/PuppetState.java
> +        unchanged(InstanceState.InstanceStateForComponentInstance.CREATED),
Lower case enum?

2020-10-14 11:25 UTC, lharzenetter commented on edmm-instance/src/main/java/io/github/edmm/plugins/puppet/model/PuppetState.java
> +public class PuppetState {
abstact

2020-10-14 11:25 UTC, lharzenetter commented on edmm-instance/src/main/java/io/github/edmm/plugins/puppet/model/Report.java
> +    String certname;
package private?

2020-10-14 11:25 UTC, lharzenetter commented on edmm-instance/src/main/java/io/github/edmm/plugins/puppet/util/Commands.java
> +class Commands {
abstract

2020-10-14 11:25 UTC, lharzenetter commented on edmm-instance/src/main/java/io/github/edmm/plugins/puppet/util/EDMMPropertyMapperImplementation.java
> +        if (specificPropertyKey.equals(Constants.TYPE)) {
switch?

2020-10-14 11:25 UTC, lharzenetter commented on edmm-instance/src/main/java/io/github/edmm/plugins/puppet/util/EDMMPropertyMapperImplementation.java
> +        if (specificPropertyKey.equals(Constants.TYPE)) {
looks similar to the heat implementation...

2020-10-14 11:25 UTC, lharzenetter commented on edmm-instance/src/main/java/io/github/edmm/plugins/puppet/util/ModuleLoader.java
> +    private static String baseURL = "https://github.com/mathonto/puppet_edimm_helper/blob/master/";
should also be passed to the CLI?

2020-10-14 11:25 UTC, lharzenetter commented on edmm-instance/src/main/java/io/github/edmm/plugins/puppet/util/PuppetConstants.java
> +class PuppetConstants {
abstract

2020-10-14 11:25 UTC, lharzenetter commented on edmm-instance/src/main/java/io/github/edmm/util/CastUtil.java
> +public class CastUtil {
abstract

2020-10-14 11:25 UTC, lharzenetter commented on edmm-instance/src/main/java/io/github/edmm/util/CastUtil.java
> +        return mapOptional.isPresent() ? castToStringObjectMap(mapOptional.get()) : Collections.emptyMap();
instead of the check, you can just use `optional.orElse(Collections.emptyMap())`

2020-10-14 11:25 UTC, lharzenetter commented on edmm-instance/src/main/java/io/github/edmm/util/CastUtil.java
> +    private static Optional<Map> checkMapForCast(Object objectToCast) {
you can add generics to avoid raw use of Map and List

2020-10-14 11:25 UTC, lharzenetter commented on edmm-instance/src/main/java/io/github/edmm/util/Constants.java
> +public class Constants {
abstract

2020-10-19 17:40 UTC, mathonto commented on edmm-instance/src/main/java/io/github/edmm/model/opentosca/TOSCAState.java
> +        INITIAL(RelationshipTemplateInstanceState.INITIAL),
It would be easier in fact, however i implemented this according to the OpenTOSCA Container State definition for Node Template Instances and Service Template Instances, which differ:

https://github.com/OpenTOSCA/container/blob/master/org.opentosca.container.core/src/main/java/org/opentosca/container/core/next/model/NodeTemplateInstanceState.java

https://github.com/OpenTOSCA/container/blob/master/org.opentosca.container.core/src/main/java/org/opentosca/container/core/next/model/ServiceTemplateInstanceState.java

2020-10-19 18:25 UTC, mathonto commented on edmm-instance/src/main/java/io/github/edmm/plugins/cfn/model/types/ACMPCAType.java
> +public enum ACMPCAType {
https://docs.aws.amazon.com/acm-pca/latest/userguide/PcaWelcome.html

2020-10-19 19:11 UTC, mathonto commented on edmm-instance/src/main/java/io/github/edmm/model/edimm/InstanceState.java
> +    public enum InstanceStateForComponentInstance {
this was also inspired by the implementation of states in OpenTOSCA (see below) and eases the mapping to these states

2020-11-03 09:20 UTC, merged