[Thesis] Multi Technology Participant Deployment
UST-EDMM/edmm pull request #28
Opened 2021-02-09 14:40 UTC by nakhadon

This PR includes work on new features including:

- Implemented extension of the EDMM model with multiple participants
- Enabling the deployment of specific components and deployment technologies through new REST-Endpoint 
- Automated generation of BPMN workflows based on the EDMM model 
- Integration of Camunda Engine for the orchestration and data exchange with other participants
- Initial GUI for the orchestration and management of the overall application deployment

2021-02-09 15:16 UTC, miwurster requested changes
First of all you should remove all `System.out` statements. Further, try to avoid `printStacktrace`. Instead use `logger.debug' and `logger.error`.

Moreover, for all DTO like classes try to use Lombok to simplify the class structure.

The most important point is to move all your stuff from the core module to the orchestration module, e.g., move your additions from the `pom.xml` as well as the added resources.

2021-02-09 15:16 UTC, miwurster commented on edmm-core/pom.xml
> +        <dependency>
Are these dependencies really required for the core module? Try to move as most as possible to the orchestration module.

2021-02-09 15:16 UTC, miwurster commented on edmm-core/pom.xml
> +        <dependency>
Why H2?

2021-02-09 15:16 UTC, miwurster commented on edmm-core/src/main/resources/plugins/choreo/MainSequence.txt
> +<#if deployTasks?has_content>
Please move the choreo stuff to the orchestration module.

2021-02-09 15:16 UTC, miwurster commented on edmm-orchestration/src/main/java/io/github/edmm/plugins/multi/kubernetes/KubernetesExecutorMulti.java
> +            System.out.println(x.getComponent());
Use logger?!

2021-02-09 15:16 UTC, miwurster commented on edmm-orchestration/src/main/java/io/github/edmm/plugins/multi/model/ComponentProperties.java
> +public class ComponentProperties implements Serializable {
Simplify class with Lombok

2021-02-09 15:16 UTC, miwurster commented on edmm-orchestration/src/main/java/io/github/edmm/plugins/multi/model/message/CamundaMessage.java
> +public class CamundaMessage {
Lombok?!

2021-02-09 15:16 UTC, miwurster commented on edmm-orchestration/src/main/java/io/github/edmm/plugins/multi/model/ComponentResources.java
>  public class ComponentResources {
Lombok?!

2021-02-09 15:16 UTC, miwurster commented on edmm-orchestration/src/main/java/io/github/edmm/plugins/multi/model/message/DeployRequest.java
> +public class DeployRequest {
Lombok?!

2021-02-09 15:16 UTC, miwurster commented on edmm-orchestration/src/main/java/io/github/edmm/plugins/multi/model/message/DeployResult.java
> +public class DeployResult {
Lombok?!

2021-02-09 15:16 UTC, miwurster commented on edmm-orchestration/src/main/java/io/github/edmm/plugins/multi/model/message/InitiateRequest.java
> +public class InitiateRequest {
Lombok?!

2021-02-09 15:16 UTC, miwurster commented on edmm-orchestration/src/main/java/io/github/edmm/plugins/multi/orchestration/camunda/DelegateHelper.java
> +        System.out.println(bpmnProperties);
Avoid System.out

2021-02-09 15:16 UTC, miwurster commented on edmm-orchestration/src/main/java/io/github/edmm/plugins/multi/orchestration/camunda/DelegateHelper.java
> +        System.out.println(propertyValue);
Remove

2021-02-09 15:16 UTC, miwurster commented on edmm-orchestration/src/main/java/io/github/edmm/plugins/multi/orchestration/camunda/DelegateHelper.java
> +            e.printStackTrace();
Use logger

2021-02-09 15:16 UTC, miwurster commented on edmm-orchestration/src/main/java/io/github/edmm/plugins/multi/orchestration/camunda/SendDelegate.java
> +            System.out.println(DelegateHelper.parseObjectToJSON(camundaMessage));
Remove

2021-02-09 15:16 UTC, miwurster commented on edmm-orchestration/src/main/java/io/github/edmm/plugins/multi/orchestration/camunda/SendDelegate.java
> +            Thread.sleep(10000);
Is this correct? Starting the "RESTCall" over and over again till the condition is true?

2021-02-09 15:16 UTC, miwurster commented on edmm-orchestration/src/main/java/io/github/edmm/plugins/multi/terraform/TerraformExecutor.java
> +        System.out.println(properties);
Remove or use logger

2021-02-09 15:16 UTC, miwurster commented on edmm-web/src/main/java/io/github/edmm/web/model/DeployResult.java
> +public class DeployResult {
Lombok!

2021-02-17 08:03 UTC, miwurster requested changes

2021-02-17 08:03 UTC, miwurster commented on edmm-web/src/main/java/io/github/edmm/web/model/DeployResult.java
> +public class DeployResult {
+1

2021-02-17 08:03 UTC, miwurster commented on edmm-web/src/main/resources/application.properties
> +repository.path=/Users/nakhadon/Projects/MA-Merge/edmm/repository
Use EnvVar and set a useful default. I suggest to revert this change.

2021-02-17 08:03 UTC, miwurster commented on edmm-web/pom.xml
> +            <scope>compile</scope>
Remove `<scope>`.

2021-02-17 08:03 UTC, miwurster commented on edmm-web/pom.xml
> +            <version>1.0.0-SNAPSHOT</version>
Use `${project.version}`

2021-02-17 08:03 UTC, miwurster commented on edmm-orchestration/src/main/java/io/github/edmm/plugins/multi/model/ComponentProperties.java
> +public class ComponentProperties implements Serializable {
+1

2021-02-17 08:26 UTC, nakhadon commented on edmm-core/pom.xml
> +        <dependency>
H2 is used for the temporary storing of property values in the current executed BPMN process. IIRC, it has to be integrated for the Camunda engine to work and store values during the process.

2021-02-17 08:30 UTC, nakhadon commented on edmm-orchestration/src/main/java/io/github/edmm/plugins/multi/orchestration/camunda/SendDelegate.java
> +            Thread.sleep(10000);
Receive Tasks can only be accessed, when they are initialized first. So, when the other participant is not done with the previous steps before the Receive Task, it can not be called, since the endpoint ist not yet accessible. The only workaround I found was to repeatedly call the endpoint until the condition is true or cancelled.

2021-02-18 08:02 UTC, miwurster approved these changes

2021-02-18 08:03 UTC, miwurster commented
One last thing before I merge... I understood that it is still possible to execute the stuff without the Camunda engine. Is this somewhere documented how to enable the Camunda-less implementation?

2021-02-18 08:40 UTC, nakhadon commented
The provided implementation by Felix has not been altered and can still be executed through the CLI. If only technology_regions are detected, the multi participant implementation is skipped.

2021-02-18 08:50 UTC, miwurster commented
Ah that's great. Could you also please document these two routes somewhere?! So, Camunda-less -> use CLI, Choreo -> use web and new "app".

2021-02-18 09:38 UTC, miwurster commented
So let's leave this PR open till the doc part is ready.

2021-03-11 10:44 UTC, nakhadon commented
I've added the documentation. If I've missed some aspects in the documentation, I can add them before we can start merging to master.

2021-03-15 11:24 UTC, miwurster approved these changes

2021-03-15 11:24 UTC, merged